/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using DynamicLeveledLists.Internals;
using ReactiveUI;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace DynamicLeveledLists
{
    #region Class
    public partial class DebugSettings : 
        LoquiNotifyingObject,
        IDebugSettings,
        ILoquiObject<DebugSettings>,
        ILoquiObjectSetter,
        IEquatable<DebugSettings>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => DebugSettings_Registration.Instance;
        public static DebugSettings_Registration Registration => DebugSettings_Registration.Instance;

        #region Ctor
        public DebugSettings()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region SpawningTracker
        private Boolean _SpawningTracker;
        public Boolean SpawningTracker
        {
            get => this._SpawningTracker;
            set => this.RaiseAndSetIfChanged(ref this._SpawningTracker, value, nameof(SpawningTracker));
        }
        #endregion
        #region InGameSpawningConsoleLogs
        private Boolean _InGameSpawningConsoleLogs;
        public Boolean InGameSpawningConsoleLogs
        {
            get => this._InGameSpawningConsoleLogs;
            set => this.RaiseAndSetIfChanged(ref this._InGameSpawningConsoleLogs, value, nameof(InGameSpawningConsoleLogs));
        }
        #endregion

        #region Loqui Getter Interface

        protected object GetNthObject(ushort index) => DebugSettingsCommon.GetNthObject(index, this);
        object ILoquiObjectGetter.GetNthObject(ushort index) => this.GetNthObject(index);

        protected bool GetNthObjectHasBeenSet(ushort index) => DebugSettingsCommon.GetNthObjectHasBeenSet(index, this);
        bool ILoquiObjectGetter.GetNthObjectHasBeenSet(ushort index) => this.GetNthObjectHasBeenSet(index);

        protected void UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => DebugSettingsCommon.UnsetNthObject(index, this, cmds);
        void ILoquiObjectSetter.UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => this.UnsetNthObject(index, cmds);

        #endregion

        #region Loqui Interface
        protected void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            DebugSettingsCommon.SetNthObjectHasBeenSet(index, on, this);
        }
        void ILoquiObjectSetter.SetNthObjectHasBeenSet(ushort index, bool on) => this.SetNthObjectHasBeenSet(index, on);

        #endregion

        IMask<bool> IEqualsMask<DebugSettings>.GetEqualsMask(DebugSettings rhs) => DebugSettingsCommon.GetEqualsMask(this, rhs);
        IMask<bool> IEqualsMask<IDebugSettingsGetter>.GetEqualsMask(IDebugSettingsGetter rhs) => DebugSettingsCommon.GetEqualsMask(this, rhs);
        #region To String
        public override string ToString()
        {
            return DebugSettingsCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            DebugSettings_Mask<bool> printMask = null)
        {
            return DebugSettingsCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            DebugSettingsCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetMask() => this.GetHasBeenSetMask();
        public DebugSettings_Mask<bool> GetHasBeenSetMask()
        {
            return DebugSettingsCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is DebugSettings rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(DebugSettings rhs)
        {
            if (rhs == null) return false;
            if (this.SpawningTracker != rhs.SpawningTracker) return false;
            if (this.InGameSpawningConsoleLogs != rhs.InGameSpawningConsoleLogs) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(SpawningTracker).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(InGameSpawningConsoleLogs).CombineHashCode(ret);
            return ret;
        }

        #endregion


        #region Xml Translation
        #region Xml Create
        [DebuggerStepThrough]
        public static DebugSettings Create_Xml(
            XElement root,
            DebugSettings_TranslationMask translationMask = null)
        {
            return Create_Xml(
                root: root,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static DebugSettings Create_Xml(
            XElement root,
            out DebugSettings_ErrorMask errorMask,
            bool doMasks = true,
            DebugSettings_TranslationMask translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = Create_Xml(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = DebugSettings_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static DebugSettings Create_Xml(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            var ret = new DebugSettings();
            try
            {
                foreach (var elem in root.Elements())
                {
                    Fill_Xml_Internal(
                        item: ret,
                        root: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static DebugSettings Create_Xml(
            string path,
            DebugSettings_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static DebugSettings Create_Xml(
            string path,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static DebugSettings Create_Xml(
            Stream stream,
            DebugSettings_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static DebugSettings Create_Xml(
            Stream stream,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        #endregion

        #region Xml Copy In
        public void CopyIn_Xml(
            XElement root,
            NotifyingFireParameters cmds = null)
        {
            CopyIn_Xml_Internal(
                root: root,
                errorMask: null,
                translationMask: null,
                cmds: cmds);
        }

        public virtual void CopyIn_Xml(
            XElement root,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask = null,
            bool doMasks = true,
            NotifyingFireParameters cmds = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyIn_Xml_Internal(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal(),
                cmds: cmds);
            errorMask = DebugSettings_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyIn_Xml_Internal(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            NotifyingFireParameters cmds = null)
        {
            LoquiXmlTranslation<DebugSettings>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        public void CopyIn_Xml(
            Stream stream,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            Stream stream,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        #endregion

        #region Xml Write
        public virtual void Write_Xml(
            XElement node,
            out DebugSettings_ErrorMask errorMask,
            bool doMasks = true,
            DebugSettings_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = DebugSettings_ErrorMask.Factory(errorMaskBuilder);
        }

        public virtual void Write_Xml(
            string path,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            topNode.Elements().First().Save(path);
        }

        public virtual void Write_Xml(
            Stream stream,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            topNode.Elements().First().Save(stream);
        }

        public void Write_Xml(
            XElement node,
            string name = null,
            DebugSettings_TranslationMask translationMask = null)
        {
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public void Write_Xml(
            string path,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            topNode.Elements().First().Save(path);
        }

        public void Write_Xml(
            Stream stream,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            topNode.Elements().First().Save(stream);
        }

        protected void Write_Xml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            DebugSettingsCommon.Write_Xml(
                item: this,
                node: node,
                name: name,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        protected static void Fill_Xml_Internal(
            DebugSettings item,
            XElement root,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "SpawningTracker":
                    try
                    {
                        errorMask?.PushIndex((int)DebugSettings_FieldIndex.SpawningTracker);
                        if (BooleanXmlTranslation.Instance.Parse(
                            root: root,
                            item: out Boolean SpawningTrackerParse,
                            errorMask: errorMask))
                        {
                            item.SpawningTracker = SpawningTrackerParse;
                        }
                        else
                        {
                            item.SpawningTracker = default(Boolean);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "InGameSpawningConsoleLogs":
                    try
                    {
                        errorMask?.PushIndex((int)DebugSettings_FieldIndex.InGameSpawningConsoleLogs);
                        if (BooleanXmlTranslation.Instance.Parse(
                            root: root,
                            item: out Boolean InGameSpawningConsoleLogsParse,
                            errorMask: errorMask))
                        {
                            item.InGameSpawningConsoleLogs = InGameSpawningConsoleLogsParse;
                        }
                        else
                        {
                            item.InGameSpawningConsoleLogs = default(Boolean);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                default:
                    break;
            }
        }

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((DebugSettings_FieldIndex)index)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return true;
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public DebugSettings Copy(
            DebugSettings_CopyMask copyMask = null,
            IDebugSettingsGetter def = null)
        {
            return DebugSettings.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static DebugSettings Copy(
            IDebugSettings item,
            DebugSettings_CopyMask copyMask = null,
            IDebugSettingsGetter def = null)
        {
            DebugSettings ret;
            if (item.GetType().Equals(typeof(DebugSettings)))
            {
                ret = new DebugSettings();
            }
            else
            {
                ret = (DebugSettings)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static DebugSettings Copy_ToLoqui(
            IDebugSettingsGetter item,
            DebugSettings_CopyMask copyMask = null,
            IDebugSettingsGetter def = null)
        {
            DebugSettings ret;
            if (item.GetType().Equals(typeof(DebugSettings)))
            {
                ret = new DebugSettings() as DebugSettings;
            }
            else
            {
                ret = (DebugSettings)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(
            IDebugSettingsGetter rhs,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: (IDebugSettingsGetter)rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IDebugSettingsGetter rhs,
            DebugSettings_CopyMask copyMask,
            IDebugSettingsGetter def = null,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IDebugSettingsGetter rhs,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_CopyMask copyMask = null,
            IDebugSettingsGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            DebugSettingsCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = DebugSettings_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            IDebugSettingsGetter rhs,
            ErrorMaskBuilder errorMask,
            DebugSettings_CopyMask copyMask = null,
            IDebugSettingsGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            DebugSettingsCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        void ILoquiObjectSetter.SetNthObject(ushort index, object obj, NotifyingFireParameters cmds) => this.SetNthObject(index, obj, cmds);
        protected void SetNthObject(ushort index, object obj, NotifyingFireParameters cmds = null)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    this.SpawningTracker = (Boolean)obj;
                    break;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    this.InGameSpawningConsoleLogs = (Boolean)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial(NotifyingUnsetParameters cmds);

        protected void CallClearPartial_Internal(NotifyingUnsetParameters cmds)
        {
            ClearPartial(cmds);
        }

        public void Clear(NotifyingUnsetParameters cmds = null)
        {
            CallClearPartial_Internal(cmds);
            DebugSettingsCommon.Clear(this, cmds);
        }


        public static DebugSettings Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new DebugSettings();
            foreach (var pair in fields)
            {
                CopyInInternal_DebugSettings(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_DebugSettings(DebugSettings obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out DebugSettings_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    obj.SpawningTracker = (Boolean)pair.Value;
                    break;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    obj.InGameSpawningConsoleLogs = (Boolean)pair.Value;
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, DebugSettings obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public partial interface IDebugSettings : IDebugSettingsGetter, ILoquiClass<IDebugSettings, IDebugSettingsGetter>, ILoquiClass<DebugSettings, IDebugSettingsGetter>
    {
        new Boolean SpawningTracker { get; set; }

        new Boolean InGameSpawningConsoleLogs { get; set; }

    }

    public partial interface IDebugSettingsGetter : ILoquiObject
    {
        #region SpawningTracker
        Boolean SpawningTracker { get; }

        #endregion
        #region InGameSpawningConsoleLogs
        Boolean InGameSpawningConsoleLogs { get; }

        #endregion

    }

    #endregion

}

namespace DynamicLeveledLists.Internals
{
    #region Field Index
    public enum DebugSettings_FieldIndex
    {
        SpawningTracker = 0,
        InGameSpawningConsoleLogs = 1,
    }
    #endregion

    #region Registration
    public class DebugSettings_Registration : ILoquiRegistration
    {
        public static readonly DebugSettings_Registration Instance = new DebugSettings_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_DynamicLeveledLists.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_DynamicLeveledLists.ProtocolKey,
            msgID: 2,
            version: 0);

        public const string GUID = "9e02a31f-3bff-45de-8bc8-fa804ac0fd1d";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(DebugSettings_Mask<>);

        public static readonly Type ErrorMaskType = typeof(DebugSettings_ErrorMask);

        public static readonly Type ClassType = typeof(DebugSettings);

        public static readonly Type GetterType = typeof(IDebugSettingsGetter);

        public static readonly Type SetterType = typeof(IDebugSettings);

        public static readonly Type CommonType = typeof(DebugSettingsCommon);

        public const string FullName = "DynamicLeveledLists.DebugSettings";

        public const string Name = "DebugSettings";

        public const string Namespace = "DynamicLeveledLists";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "SPAWNINGTRACKER":
                    return (ushort)DebugSettings_FieldIndex.SpawningTracker;
                case "INGAMESPAWNINGCONSOLELOGS":
                    return (ushort)DebugSettings_FieldIndex.InGameSpawningConsoleLogs;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    return "SpawningTracker";
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return "InGameSpawningConsoleLogs";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    return typeof(Boolean);
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return typeof(Boolean);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class DebugSettingsCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            IDebugSettings item,
            IDebugSettingsGetter rhs,
            IDebugSettingsGetter def,
            ErrorMaskBuilder errorMask,
            DebugSettings_CopyMask copyMask,
            NotifyingFireParameters cmds = null)
        {
            if (copyMask?.SpawningTracker ?? true)
            {
                errorMask?.PushIndex((int)DebugSettings_FieldIndex.SpawningTracker);
                try
                {
                    item.SpawningTracker = rhs.SpawningTracker;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.InGameSpawningConsoleLogs ?? true)
            {
                errorMask?.PushIndex((int)DebugSettings_FieldIndex.InGameSpawningConsoleLogs);
                try
                {
                    item.InGameSpawningConsoleLogs = rhs.InGameSpawningConsoleLogs;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            IDebugSettings obj,
            NotifyingFireParameters cmds = null)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    if (on) break;
                    throw new ArgumentException("Tried to unset a field which does not have this functionality." + index);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void UnsetNthObject(
            ushort index,
            IDebugSettings obj,
            NotifyingUnsetParameters cmds = null)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    obj.SpawningTracker = default(Boolean);
                    break;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    obj.InGameSpawningConsoleLogs = default(Boolean);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            IDebugSettings obj)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static object GetNthObject(
            ushort index,
            IDebugSettingsGetter obj)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    return obj.SpawningTracker;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return obj.InGameSpawningConsoleLogs;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void Clear(
            IDebugSettings item,
            NotifyingUnsetParameters cmds = null)
        {
            item.SpawningTracker = default(Boolean);
            item.InGameSpawningConsoleLogs = default(Boolean);
        }

        public static DebugSettings_Mask<bool> GetEqualsMask(
            this IDebugSettingsGetter item,
            IDebugSettingsGetter rhs)
        {
            var ret = new DebugSettings_Mask<bool>();
            FillEqualsMask(item, rhs, ret);
            return ret;
        }

        public static void FillEqualsMask(
            IDebugSettingsGetter item,
            IDebugSettingsGetter rhs,
            DebugSettings_Mask<bool> ret)
        {
            if (rhs == null) return;
            ret.SpawningTracker = item.SpawningTracker == rhs.SpawningTracker;
            ret.InGameSpawningConsoleLogs = item.InGameSpawningConsoleLogs == rhs.InGameSpawningConsoleLogs;
        }

        public static string ToString(
            this IDebugSettingsGetter item,
            string name = null,
            DebugSettings_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this IDebugSettingsGetter item,
            FileGeneration fg,
            string name = null,
            DebugSettings_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(DebugSettings)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(DebugSettings)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.SpawningTracker ?? true)
                {
                    fg.AppendLine($"SpawningTracker => {item.SpawningTracker}");
                }
                if (printMask?.InGameSpawningConsoleLogs ?? true)
                {
                    fg.AppendLine($"InGameSpawningConsoleLogs => {item.InGameSpawningConsoleLogs}");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this IDebugSettingsGetter item,
            DebugSettings_Mask<bool?> checkMask)
        {
            return true;
        }

        public static DebugSettings_Mask<bool> GetHasBeenSetMask(IDebugSettingsGetter item)
        {
            var ret = new DebugSettings_Mask<bool>();
            ret.SpawningTracker = true;
            ret.InGameSpawningConsoleLogs = true;
            return ret;
        }

        #region Xml Translation
        #region Xml Write
        public static void Write_Xml(
            XElement node,
            DebugSettings item,
            bool doMasks,
            out DebugSettings_ErrorMask errorMask,
            DebugSettings_TranslationMask translationMask,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            Write_Xml(
                node: node,
                name: name,
                item: item,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = DebugSettings_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void Write_Xml(
            XElement node,
            DebugSettings item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "DynamicLeveledLists.DebugSettings");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "DynamicLeveledLists.DebugSettings");
            }
            if ((translationMask?.GetShouldTranslate((int)DebugSettings_FieldIndex.SpawningTracker) ?? true))
            {
                BooleanXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.SpawningTracker),
                    item: item.SpawningTracker,
                    fieldIndex: (int)DebugSettings_FieldIndex.SpawningTracker,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)DebugSettings_FieldIndex.InGameSpawningConsoleLogs) ?? true))
            {
                BooleanXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.InGameSpawningConsoleLogs),
                    item: item.InGameSpawningConsoleLogs,
                    fieldIndex: (int)DebugSettings_FieldIndex.InGameSpawningConsoleLogs,
                    errorMask: errorMask);
            }
        }
        #endregion

        #endregion

    }
    #endregion

    #region Modules
    #region Mask
    public class DebugSettings_Mask<T> : IMask<T>, IEquatable<DebugSettings_Mask<T>>
    {
        #region Ctors
        public DebugSettings_Mask()
        {
        }

        public DebugSettings_Mask(T initialValue)
        {
            this.SpawningTracker = initialValue;
            this.InGameSpawningConsoleLogs = initialValue;
        }
        #endregion

        #region Members
        public T SpawningTracker;
        public T InGameSpawningConsoleLogs;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is DebugSettings_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(DebugSettings_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.SpawningTracker, rhs.SpawningTracker)) return false;
            if (!object.Equals(this.InGameSpawningConsoleLogs, rhs.InGameSpawningConsoleLogs)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.SpawningTracker?.GetHashCode());
            ret = ret.CombineHashCode(this.InGameSpawningConsoleLogs?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.SpawningTracker)) return false;
            if (!eval(this.InGameSpawningConsoleLogs)) return false;
            return true;
        }
        #endregion

        #region Translate
        public DebugSettings_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new DebugSettings_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(DebugSettings_Mask<R> obj, Func<T, R> eval)
        {
            obj.SpawningTracker = eval(this.SpawningTracker);
            obj.InGameSpawningConsoleLogs = eval(this.InGameSpawningConsoleLogs);
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(DebugSettings_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, DebugSettings_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(DebugSettings_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.SpawningTracker ?? true)
                {
                    fg.AppendLine($"SpawningTracker => {SpawningTracker}");
                }
                if (printMask?.InGameSpawningConsoleLogs ?? true)
                {
                    fg.AppendLine($"InGameSpawningConsoleLogs => {InGameSpawningConsoleLogs}");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class DebugSettings_ErrorMask : IErrorMask, IErrorMask<DebugSettings_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception SpawningTracker;
        public Exception InGameSpawningConsoleLogs;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    return SpawningTracker;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    return InGameSpawningConsoleLogs;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    this.SpawningTracker = ex;
                    break;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    this.InGameSpawningConsoleLogs = ex;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            DebugSettings_FieldIndex enu = (DebugSettings_FieldIndex)index;
            switch (enu)
            {
                case DebugSettings_FieldIndex.SpawningTracker:
                    this.SpawningTracker = (Exception)obj;
                    break;
                case DebugSettings_FieldIndex.InGameSpawningConsoleLogs:
                    this.InGameSpawningConsoleLogs = (Exception)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (SpawningTracker != null) return true;
            if (InGameSpawningConsoleLogs != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("DebugSettings_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"SpawningTracker => {SpawningTracker}");
            fg.AppendLine($"InGameSpawningConsoleLogs => {InGameSpawningConsoleLogs}");
        }
        #endregion

        #region Combine
        public DebugSettings_ErrorMask Combine(DebugSettings_ErrorMask rhs)
        {
            var ret = new DebugSettings_ErrorMask();
            ret.SpawningTracker = this.SpawningTracker.Combine(rhs.SpawningTracker);
            ret.InGameSpawningConsoleLogs = this.InGameSpawningConsoleLogs.Combine(rhs.InGameSpawningConsoleLogs);
            return ret;
        }
        public static DebugSettings_ErrorMask Combine(DebugSettings_ErrorMask lhs, DebugSettings_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static DebugSettings_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new DebugSettings_ErrorMask();
        }
        #endregion

    }
    public class DebugSettings_CopyMask
    {
        public DebugSettings_CopyMask()
        {
        }

        public DebugSettings_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.SpawningTracker = defaultOn;
            this.InGameSpawningConsoleLogs = defaultOn;
        }

        #region Members
        public bool SpawningTracker;
        public bool InGameSpawningConsoleLogs;
        #endregion

    }

    public class DebugSettings_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool SpawningTracker;
        public bool InGameSpawningConsoleLogs;
        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((SpawningTracker, null));
            ret.Add((InGameSpawningConsoleLogs, null));
        }
    }
    #endregion

    #endregion

}
