/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using DynamicLeveledLists.Internals;
using ReactiveUI;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace DynamicLeveledLists
{
    #region Class
    public partial class SpawningPerformance : 
        LoquiNotifyingObject,
        ISpawningPerformance,
        ILoquiObject<SpawningPerformance>,
        ILoquiObjectSetter,
        IEquatable<SpawningPerformance>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => SpawningPerformance_Registration.Instance;
        public static SpawningPerformance_Registration Registration => SpawningPerformance_Registration.Instance;

        #region Ctor
        public SpawningPerformance()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Delay
        private Boolean _Delay;
        public Boolean Delay
        {
            get => this._Delay;
            set => this.RaiseAndSetIfChanged(ref this._Delay, value, nameof(Delay));
        }
        #endregion
        #region Confirm
        private Boolean _Confirm;
        public Boolean Confirm
        {
            get => this._Confirm;
            set => this.RaiseAndSetIfChanged(ref this._Confirm, value, nameof(Confirm));
        }
        #endregion
        #region Cleanup
        private Boolean _Cleanup;
        public Boolean Cleanup
        {
            get => this._Cleanup;
            set => this.RaiseAndSetIfChanged(ref this._Cleanup, value, nameof(Cleanup));
        }
        #endregion
        #region CleanupBatch
        private Int16 _CleanupBatch;
        public Int16 CleanupBatch
        {
            get => this._CleanupBatch;
            set => this.RaiseAndSetIfChanged(ref this._CleanupBatch, value, nameof(CleanupBatch));
        }
        #endregion

        #region Loqui Getter Interface

        protected object GetNthObject(ushort index) => SpawningPerformanceCommon.GetNthObject(index, this);
        object ILoquiObjectGetter.GetNthObject(ushort index) => this.GetNthObject(index);

        protected bool GetNthObjectHasBeenSet(ushort index) => SpawningPerformanceCommon.GetNthObjectHasBeenSet(index, this);
        bool ILoquiObjectGetter.GetNthObjectHasBeenSet(ushort index) => this.GetNthObjectHasBeenSet(index);

        protected void UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => SpawningPerformanceCommon.UnsetNthObject(index, this, cmds);
        void ILoquiObjectSetter.UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => this.UnsetNthObject(index, cmds);

        #endregion

        #region Loqui Interface
        protected void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            SpawningPerformanceCommon.SetNthObjectHasBeenSet(index, on, this);
        }
        void ILoquiObjectSetter.SetNthObjectHasBeenSet(ushort index, bool on) => this.SetNthObjectHasBeenSet(index, on);

        #endregion

        IMask<bool> IEqualsMask<SpawningPerformance>.GetEqualsMask(SpawningPerformance rhs) => SpawningPerformanceCommon.GetEqualsMask(this, rhs);
        IMask<bool> IEqualsMask<ISpawningPerformanceGetter>.GetEqualsMask(ISpawningPerformanceGetter rhs) => SpawningPerformanceCommon.GetEqualsMask(this, rhs);
        #region To String
        public override string ToString()
        {
            return SpawningPerformanceCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            SpawningPerformance_Mask<bool> printMask = null)
        {
            return SpawningPerformanceCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            SpawningPerformanceCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetMask() => this.GetHasBeenSetMask();
        public SpawningPerformance_Mask<bool> GetHasBeenSetMask()
        {
            return SpawningPerformanceCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is SpawningPerformance rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(SpawningPerformance rhs)
        {
            if (rhs == null) return false;
            if (this.Delay != rhs.Delay) return false;
            if (this.Confirm != rhs.Confirm) return false;
            if (this.Cleanup != rhs.Cleanup) return false;
            if (this.CleanupBatch != rhs.CleanupBatch) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(Delay).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(Confirm).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(Cleanup).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(CleanupBatch).CombineHashCode(ret);
            return ret;
        }

        #endregion


        #region Xml Translation
        #region Xml Create
        [DebuggerStepThrough]
        public static SpawningPerformance Create_Xml(
            XElement root,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            return Create_Xml(
                root: root,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static SpawningPerformance Create_Xml(
            XElement root,
            out SpawningPerformance_ErrorMask errorMask,
            bool doMasks = true,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = Create_Xml(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = SpawningPerformance_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static SpawningPerformance Create_Xml(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            var ret = new SpawningPerformance();
            try
            {
                foreach (var elem in root.Elements())
                {
                    Fill_Xml_Internal(
                        item: ret,
                        root: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static SpawningPerformance Create_Xml(
            string path,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static SpawningPerformance Create_Xml(
            string path,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static SpawningPerformance Create_Xml(
            Stream stream,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static SpawningPerformance Create_Xml(
            Stream stream,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        #endregion

        #region Xml Copy In
        public void CopyIn_Xml(
            XElement root,
            NotifyingFireParameters cmds = null)
        {
            CopyIn_Xml_Internal(
                root: root,
                errorMask: null,
                translationMask: null,
                cmds: cmds);
        }

        public virtual void CopyIn_Xml(
            XElement root,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask = null,
            bool doMasks = true,
            NotifyingFireParameters cmds = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyIn_Xml_Internal(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal(),
                cmds: cmds);
            errorMask = SpawningPerformance_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyIn_Xml_Internal(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            NotifyingFireParameters cmds = null)
        {
            LoquiXmlTranslation<SpawningPerformance>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        public void CopyIn_Xml(
            Stream stream,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            Stream stream,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        #endregion

        #region Xml Write
        public virtual void Write_Xml(
            XElement node,
            out SpawningPerformance_ErrorMask errorMask,
            bool doMasks = true,
            SpawningPerformance_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = SpawningPerformance_ErrorMask.Factory(errorMaskBuilder);
        }

        public virtual void Write_Xml(
            string path,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            topNode.Elements().First().Save(path);
        }

        public virtual void Write_Xml(
            Stream stream,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            topNode.Elements().First().Save(stream);
        }

        public void Write_Xml(
            XElement node,
            string name = null,
            SpawningPerformance_TranslationMask translationMask = null)
        {
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public void Write_Xml(
            string path,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            topNode.Elements().First().Save(path);
        }

        public void Write_Xml(
            Stream stream,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            topNode.Elements().First().Save(stream);
        }

        protected void Write_Xml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            SpawningPerformanceCommon.Write_Xml(
                item: this,
                node: node,
                name: name,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        protected static void Fill_Xml_Internal(
            SpawningPerformance item,
            XElement root,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "Delay":
                    try
                    {
                        errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Delay);
                        if (BooleanXmlTranslation.Instance.Parse(
                            root: root,
                            item: out Boolean DelayParse,
                            errorMask: errorMask))
                        {
                            item.Delay = DelayParse;
                        }
                        else
                        {
                            item.Delay = default(Boolean);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "Confirm":
                    try
                    {
                        errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Confirm);
                        if (BooleanXmlTranslation.Instance.Parse(
                            root: root,
                            item: out Boolean ConfirmParse,
                            errorMask: errorMask))
                        {
                            item.Confirm = ConfirmParse;
                        }
                        else
                        {
                            item.Confirm = default(Boolean);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "Cleanup":
                    try
                    {
                        errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Cleanup);
                        if (BooleanXmlTranslation.Instance.Parse(
                            root: root,
                            item: out Boolean CleanupParse,
                            errorMask: errorMask))
                        {
                            item.Cleanup = CleanupParse;
                        }
                        else
                        {
                            item.Cleanup = default(Boolean);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "CleanupBatch":
                    try
                    {
                        errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.CleanupBatch);
                        if (Int16XmlTranslation.Instance.Parse(
                            root: root,
                            item: out Int16 CleanupBatchParse,
                            errorMask: errorMask))
                        {
                            item.CleanupBatch = CleanupBatchParse;
                        }
                        else
                        {
                            item.CleanupBatch = default(Int16);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                default:
                    break;
            }
        }

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((SpawningPerformance_FieldIndex)index)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return true;
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public SpawningPerformance Copy(
            SpawningPerformance_CopyMask copyMask = null,
            ISpawningPerformanceGetter def = null)
        {
            return SpawningPerformance.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static SpawningPerformance Copy(
            ISpawningPerformance item,
            SpawningPerformance_CopyMask copyMask = null,
            ISpawningPerformanceGetter def = null)
        {
            SpawningPerformance ret;
            if (item.GetType().Equals(typeof(SpawningPerformance)))
            {
                ret = new SpawningPerformance();
            }
            else
            {
                ret = (SpawningPerformance)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static SpawningPerformance Copy_ToLoqui(
            ISpawningPerformanceGetter item,
            SpawningPerformance_CopyMask copyMask = null,
            ISpawningPerformanceGetter def = null)
        {
            SpawningPerformance ret;
            if (item.GetType().Equals(typeof(SpawningPerformance)))
            {
                ret = new SpawningPerformance() as SpawningPerformance;
            }
            else
            {
                ret = (SpawningPerformance)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(
            ISpawningPerformanceGetter rhs,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: (ISpawningPerformanceGetter)rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            ISpawningPerformanceGetter rhs,
            SpawningPerformance_CopyMask copyMask,
            ISpawningPerformanceGetter def = null,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            ISpawningPerformanceGetter rhs,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_CopyMask copyMask = null,
            ISpawningPerformanceGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            SpawningPerformanceCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = SpawningPerformance_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            ISpawningPerformanceGetter rhs,
            ErrorMaskBuilder errorMask,
            SpawningPerformance_CopyMask copyMask = null,
            ISpawningPerformanceGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            SpawningPerformanceCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        void ILoquiObjectSetter.SetNthObject(ushort index, object obj, NotifyingFireParameters cmds) => this.SetNthObject(index, obj, cmds);
        protected void SetNthObject(ushort index, object obj, NotifyingFireParameters cmds = null)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    this.Delay = (Boolean)obj;
                    break;
                case SpawningPerformance_FieldIndex.Confirm:
                    this.Confirm = (Boolean)obj;
                    break;
                case SpawningPerformance_FieldIndex.Cleanup:
                    this.Cleanup = (Boolean)obj;
                    break;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    this.CleanupBatch = (Int16)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial(NotifyingUnsetParameters cmds);

        protected void CallClearPartial_Internal(NotifyingUnsetParameters cmds)
        {
            ClearPartial(cmds);
        }

        public void Clear(NotifyingUnsetParameters cmds = null)
        {
            CallClearPartial_Internal(cmds);
            SpawningPerformanceCommon.Clear(this, cmds);
        }


        public static SpawningPerformance Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new SpawningPerformance();
            foreach (var pair in fields)
            {
                CopyInInternal_SpawningPerformance(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_SpawningPerformance(SpawningPerformance obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out SpawningPerformance_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    obj.Delay = (Boolean)pair.Value;
                    break;
                case SpawningPerformance_FieldIndex.Confirm:
                    obj.Confirm = (Boolean)pair.Value;
                    break;
                case SpawningPerformance_FieldIndex.Cleanup:
                    obj.Cleanup = (Boolean)pair.Value;
                    break;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    obj.CleanupBatch = (Int16)pair.Value;
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, SpawningPerformance obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public partial interface ISpawningPerformance : ISpawningPerformanceGetter, ILoquiClass<ISpawningPerformance, ISpawningPerformanceGetter>, ILoquiClass<SpawningPerformance, ISpawningPerformanceGetter>
    {
        new Boolean Delay { get; set; }

        new Boolean Confirm { get; set; }

        new Boolean Cleanup { get; set; }

        new Int16 CleanupBatch { get; set; }

    }

    public partial interface ISpawningPerformanceGetter : ILoquiObject
    {
        #region Delay
        Boolean Delay { get; }

        #endregion
        #region Confirm
        Boolean Confirm { get; }

        #endregion
        #region Cleanup
        Boolean Cleanup { get; }

        #endregion
        #region CleanupBatch
        Int16 CleanupBatch { get; }

        #endregion

    }

    #endregion

}

namespace DynamicLeveledLists.Internals
{
    #region Field Index
    public enum SpawningPerformance_FieldIndex
    {
        Delay = 0,
        Confirm = 1,
        Cleanup = 2,
        CleanupBatch = 3,
    }
    #endregion

    #region Registration
    public class SpawningPerformance_Registration : ILoquiRegistration
    {
        public static readonly SpawningPerformance_Registration Instance = new SpawningPerformance_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_DynamicLeveledLists.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_DynamicLeveledLists.ProtocolKey,
            msgID: 5,
            version: 0);

        public const string GUID = "fbebf620-18df-4b6f-954b-346bc2d4e111";

        public const ushort AdditionalFieldCount = 4;

        public const ushort FieldCount = 4;

        public static readonly Type MaskType = typeof(SpawningPerformance_Mask<>);

        public static readonly Type ErrorMaskType = typeof(SpawningPerformance_ErrorMask);

        public static readonly Type ClassType = typeof(SpawningPerformance);

        public static readonly Type GetterType = typeof(ISpawningPerformanceGetter);

        public static readonly Type SetterType = typeof(ISpawningPerformance);

        public static readonly Type CommonType = typeof(SpawningPerformanceCommon);

        public const string FullName = "DynamicLeveledLists.SpawningPerformance";

        public const string Name = "SpawningPerformance";

        public const string Namespace = "DynamicLeveledLists";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "DELAY":
                    return (ushort)SpawningPerformance_FieldIndex.Delay;
                case "CONFIRM":
                    return (ushort)SpawningPerformance_FieldIndex.Confirm;
                case "CLEANUP":
                    return (ushort)SpawningPerformance_FieldIndex.Cleanup;
                case "CLEANUPBATCH":
                    return (ushort)SpawningPerformance_FieldIndex.CleanupBatch;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    return "Delay";
                case SpawningPerformance_FieldIndex.Confirm:
                    return "Confirm";
                case SpawningPerformance_FieldIndex.Cleanup:
                    return "Cleanup";
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return "CleanupBatch";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    return typeof(Boolean);
                case SpawningPerformance_FieldIndex.Confirm:
                    return typeof(Boolean);
                case SpawningPerformance_FieldIndex.Cleanup:
                    return typeof(Boolean);
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return typeof(Int16);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class SpawningPerformanceCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            ISpawningPerformance item,
            ISpawningPerformanceGetter rhs,
            ISpawningPerformanceGetter def,
            ErrorMaskBuilder errorMask,
            SpawningPerformance_CopyMask copyMask,
            NotifyingFireParameters cmds = null)
        {
            if (copyMask?.Delay ?? true)
            {
                errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Delay);
                try
                {
                    item.Delay = rhs.Delay;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.Confirm ?? true)
            {
                errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Confirm);
                try
                {
                    item.Confirm = rhs.Confirm;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.Cleanup ?? true)
            {
                errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.Cleanup);
                try
                {
                    item.Cleanup = rhs.Cleanup;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.CleanupBatch ?? true)
            {
                errorMask?.PushIndex((int)SpawningPerformance_FieldIndex.CleanupBatch);
                try
                {
                    item.CleanupBatch = rhs.CleanupBatch;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            ISpawningPerformance obj,
            NotifyingFireParameters cmds = null)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    if (on) break;
                    throw new ArgumentException("Tried to unset a field which does not have this functionality." + index);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void UnsetNthObject(
            ushort index,
            ISpawningPerformance obj,
            NotifyingUnsetParameters cmds = null)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    obj.Delay = default(Boolean);
                    break;
                case SpawningPerformance_FieldIndex.Confirm:
                    obj.Confirm = default(Boolean);
                    break;
                case SpawningPerformance_FieldIndex.Cleanup:
                    obj.Cleanup = default(Boolean);
                    break;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    obj.CleanupBatch = default(Int16);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            ISpawningPerformance obj)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                case SpawningPerformance_FieldIndex.Confirm:
                case SpawningPerformance_FieldIndex.Cleanup:
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static object GetNthObject(
            ushort index,
            ISpawningPerformanceGetter obj)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    return obj.Delay;
                case SpawningPerformance_FieldIndex.Confirm:
                    return obj.Confirm;
                case SpawningPerformance_FieldIndex.Cleanup:
                    return obj.Cleanup;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return obj.CleanupBatch;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void Clear(
            ISpawningPerformance item,
            NotifyingUnsetParameters cmds = null)
        {
            item.Delay = default(Boolean);
            item.Confirm = default(Boolean);
            item.Cleanup = default(Boolean);
            item.CleanupBatch = default(Int16);
        }

        public static SpawningPerformance_Mask<bool> GetEqualsMask(
            this ISpawningPerformanceGetter item,
            ISpawningPerformanceGetter rhs)
        {
            var ret = new SpawningPerformance_Mask<bool>();
            FillEqualsMask(item, rhs, ret);
            return ret;
        }

        public static void FillEqualsMask(
            ISpawningPerformanceGetter item,
            ISpawningPerformanceGetter rhs,
            SpawningPerformance_Mask<bool> ret)
        {
            if (rhs == null) return;
            ret.Delay = item.Delay == rhs.Delay;
            ret.Confirm = item.Confirm == rhs.Confirm;
            ret.Cleanup = item.Cleanup == rhs.Cleanup;
            ret.CleanupBatch = item.CleanupBatch == rhs.CleanupBatch;
        }

        public static string ToString(
            this ISpawningPerformanceGetter item,
            string name = null,
            SpawningPerformance_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this ISpawningPerformanceGetter item,
            FileGeneration fg,
            string name = null,
            SpawningPerformance_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(SpawningPerformance)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(SpawningPerformance)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Delay ?? true)
                {
                    fg.AppendLine($"Delay => {item.Delay}");
                }
                if (printMask?.Confirm ?? true)
                {
                    fg.AppendLine($"Confirm => {item.Confirm}");
                }
                if (printMask?.Cleanup ?? true)
                {
                    fg.AppendLine($"Cleanup => {item.Cleanup}");
                }
                if (printMask?.CleanupBatch ?? true)
                {
                    fg.AppendLine($"CleanupBatch => {item.CleanupBatch}");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this ISpawningPerformanceGetter item,
            SpawningPerformance_Mask<bool?> checkMask)
        {
            return true;
        }

        public static SpawningPerformance_Mask<bool> GetHasBeenSetMask(ISpawningPerformanceGetter item)
        {
            var ret = new SpawningPerformance_Mask<bool>();
            ret.Delay = true;
            ret.Confirm = true;
            ret.Cleanup = true;
            ret.CleanupBatch = true;
            return ret;
        }

        #region Xml Translation
        #region Xml Write
        public static void Write_Xml(
            XElement node,
            SpawningPerformance item,
            bool doMasks,
            out SpawningPerformance_ErrorMask errorMask,
            SpawningPerformance_TranslationMask translationMask,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            Write_Xml(
                node: node,
                name: name,
                item: item,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = SpawningPerformance_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void Write_Xml(
            XElement node,
            SpawningPerformance item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "DynamicLeveledLists.SpawningPerformance");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "DynamicLeveledLists.SpawningPerformance");
            }
            if ((translationMask?.GetShouldTranslate((int)SpawningPerformance_FieldIndex.Delay) ?? true))
            {
                BooleanXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.Delay),
                    item: item.Delay,
                    fieldIndex: (int)SpawningPerformance_FieldIndex.Delay,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)SpawningPerformance_FieldIndex.Confirm) ?? true))
            {
                BooleanXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.Confirm),
                    item: item.Confirm,
                    fieldIndex: (int)SpawningPerformance_FieldIndex.Confirm,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)SpawningPerformance_FieldIndex.Cleanup) ?? true))
            {
                BooleanXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.Cleanup),
                    item: item.Cleanup,
                    fieldIndex: (int)SpawningPerformance_FieldIndex.Cleanup,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)SpawningPerformance_FieldIndex.CleanupBatch) ?? true))
            {
                Int16XmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.CleanupBatch),
                    item: item.CleanupBatch,
                    fieldIndex: (int)SpawningPerformance_FieldIndex.CleanupBatch,
                    errorMask: errorMask);
            }
        }
        #endregion

        #endregion

    }
    #endregion

    #region Modules
    #region Mask
    public class SpawningPerformance_Mask<T> : IMask<T>, IEquatable<SpawningPerformance_Mask<T>>
    {
        #region Ctors
        public SpawningPerformance_Mask()
        {
        }

        public SpawningPerformance_Mask(T initialValue)
        {
            this.Delay = initialValue;
            this.Confirm = initialValue;
            this.Cleanup = initialValue;
            this.CleanupBatch = initialValue;
        }
        #endregion

        #region Members
        public T Delay;
        public T Confirm;
        public T Cleanup;
        public T CleanupBatch;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is SpawningPerformance_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(SpawningPerformance_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Delay, rhs.Delay)) return false;
            if (!object.Equals(this.Confirm, rhs.Confirm)) return false;
            if (!object.Equals(this.Cleanup, rhs.Cleanup)) return false;
            if (!object.Equals(this.CleanupBatch, rhs.CleanupBatch)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Delay?.GetHashCode());
            ret = ret.CombineHashCode(this.Confirm?.GetHashCode());
            ret = ret.CombineHashCode(this.Cleanup?.GetHashCode());
            ret = ret.CombineHashCode(this.CleanupBatch?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.Delay)) return false;
            if (!eval(this.Confirm)) return false;
            if (!eval(this.Cleanup)) return false;
            if (!eval(this.CleanupBatch)) return false;
            return true;
        }
        #endregion

        #region Translate
        public SpawningPerformance_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new SpawningPerformance_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(SpawningPerformance_Mask<R> obj, Func<T, R> eval)
        {
            obj.Delay = eval(this.Delay);
            obj.Confirm = eval(this.Confirm);
            obj.Cleanup = eval(this.Cleanup);
            obj.CleanupBatch = eval(this.CleanupBatch);
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(SpawningPerformance_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, SpawningPerformance_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(SpawningPerformance_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Delay ?? true)
                {
                    fg.AppendLine($"Delay => {Delay}");
                }
                if (printMask?.Confirm ?? true)
                {
                    fg.AppendLine($"Confirm => {Confirm}");
                }
                if (printMask?.Cleanup ?? true)
                {
                    fg.AppendLine($"Cleanup => {Cleanup}");
                }
                if (printMask?.CleanupBatch ?? true)
                {
                    fg.AppendLine($"CleanupBatch => {CleanupBatch}");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class SpawningPerformance_ErrorMask : IErrorMask, IErrorMask<SpawningPerformance_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception Delay;
        public Exception Confirm;
        public Exception Cleanup;
        public Exception CleanupBatch;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    return Delay;
                case SpawningPerformance_FieldIndex.Confirm:
                    return Confirm;
                case SpawningPerformance_FieldIndex.Cleanup:
                    return Cleanup;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    return CleanupBatch;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    this.Delay = ex;
                    break;
                case SpawningPerformance_FieldIndex.Confirm:
                    this.Confirm = ex;
                    break;
                case SpawningPerformance_FieldIndex.Cleanup:
                    this.Cleanup = ex;
                    break;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    this.CleanupBatch = ex;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            SpawningPerformance_FieldIndex enu = (SpawningPerformance_FieldIndex)index;
            switch (enu)
            {
                case SpawningPerformance_FieldIndex.Delay:
                    this.Delay = (Exception)obj;
                    break;
                case SpawningPerformance_FieldIndex.Confirm:
                    this.Confirm = (Exception)obj;
                    break;
                case SpawningPerformance_FieldIndex.Cleanup:
                    this.Cleanup = (Exception)obj;
                    break;
                case SpawningPerformance_FieldIndex.CleanupBatch:
                    this.CleanupBatch = (Exception)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (Delay != null) return true;
            if (Confirm != null) return true;
            if (Cleanup != null) return true;
            if (CleanupBatch != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("SpawningPerformance_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"Delay => {Delay}");
            fg.AppendLine($"Confirm => {Confirm}");
            fg.AppendLine($"Cleanup => {Cleanup}");
            fg.AppendLine($"CleanupBatch => {CleanupBatch}");
        }
        #endregion

        #region Combine
        public SpawningPerformance_ErrorMask Combine(SpawningPerformance_ErrorMask rhs)
        {
            var ret = new SpawningPerformance_ErrorMask();
            ret.Delay = this.Delay.Combine(rhs.Delay);
            ret.Confirm = this.Confirm.Combine(rhs.Confirm);
            ret.Cleanup = this.Cleanup.Combine(rhs.Cleanup);
            ret.CleanupBatch = this.CleanupBatch.Combine(rhs.CleanupBatch);
            return ret;
        }
        public static SpawningPerformance_ErrorMask Combine(SpawningPerformance_ErrorMask lhs, SpawningPerformance_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static SpawningPerformance_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new SpawningPerformance_ErrorMask();
        }
        #endregion

    }
    public class SpawningPerformance_CopyMask
    {
        public SpawningPerformance_CopyMask()
        {
        }

        public SpawningPerformance_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.Delay = defaultOn;
            this.Confirm = defaultOn;
            this.Cleanup = defaultOn;
            this.CleanupBatch = defaultOn;
        }

        #region Members
        public bool Delay;
        public bool Confirm;
        public bool Cleanup;
        public bool CleanupBatch;
        #endregion

    }

    public class SpawningPerformance_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool Delay;
        public bool Confirm;
        public bool Cleanup;
        public bool CleanupBatch;
        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((Delay, null));
            ret.Add((Confirm, null));
            ret.Add((Cleanup, null));
            ret.Add((CleanupBatch, null));
        }
    }
    #endregion

    #endregion

}
